## modules and packages
## map(),filter(),lambda
## list and dictoinary comprehensions
## Numpy

### modules and packages

In [2]:
import math

In [3]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of

## moduleName.funcName

In [4]:
math.sqrt(4)

2.0

In [5]:
math.sqrt(36)

6.0

In [6]:
math.pow(2,5)

32.0

In [7]:
math.radians(90)

1.5707963267948966

In [10]:
rad = math.radians(45)
rad

0.7853981633974483

In [11]:
math.cos(rad)

0.7071067811865476

In [12]:
1/(2 ** 0.5)

0.7071067811865475

In [13]:
math.ceil(8.5)

9

In [16]:
math.floor(8.5)

8

In [17]:
math.factorial(5)

120

## import moduleName as alaisName

In [18]:
import math as m

In [19]:
m.pow(5,2)

25.0

In [20]:
from math import sqrt

In [21]:
sqrt(4)

2.0

In [22]:
from math import sqrt,pow

In [23]:
pow(5,2)

25.0

In [24]:
from math import *

In [25]:
ceil(8.9)

9

In [26]:
floor(8.9)

8

In [27]:
pow(5,2)

25.0

In [40]:
import myMouni

In [41]:
myMouni.add(2,5)

7

In [42]:
myMouni.mul(2,5)

10

In [43]:
myMouni.pi

3.14

## NUMPY

In [2]:
import numpy as np

In [45]:
n1 = np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [48]:
n2 = np.array([1,2,3,4,5.0])
n2

array([1., 2., 3., 4., 5.])

In [49]:
type(n1)

numpy.ndarray

In [50]:
n1.dtype

dtype('int32')

In [51]:
n2.dtype

dtype('float64')

In [52]:
n1.ndim

1

In [53]:
d2 = np.array([[1,2],[3,4]])
d2

array([[1, 2],
       [3, 4]])

In [54]:
d2.ndim

2

In [58]:
n3 = np.arange(30)
n3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
n4 = np.arange(1,51,2)
n4

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [28]:
n4.shape

(25,)

In [29]:
n4 = n4.reshape(5,5)

In [39]:
n4

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [31]:
n4[0]

array([1, 3, 5, 7, 9])

In [32]:
n4[0,2]

5

In [33]:
n4[:2,:2]

array([[ 1,  3],
       [11, 13]])

In [70]:
n = np.arange(1,51)
li = [i for i in range(1,51)]

print(n)
print(li)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [72]:
%timeit [i ** 2 for i in li]

18.5 µs ± 122 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [75]:
%timeit n ** 2

611 ns ± 7.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## mathematical operations

In [3]:
n1 = np.arange(1,11)
n2 = np.arange(1,11)

In [4]:
n1 + n2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
n1 * n2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
n1 == n2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [7]:
np.logical_and(n1,n2)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
np.logical_not(n1)

array([False, False, False, False, False, False, False, False, False,
       False])

In [9]:
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
n2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.logical_and(np.array([0,1,2]),np.array([2,3,4]))

array([False,  True,  True])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [16]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
d = np.diag([1,2,3,4,5])
d

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [44]:
d.diagonal()

array([1, 2, 3, 4, 5])

In [45]:
n4.diagonal()

array([ 1, 13, 25, 37, 49])

In [46]:
np.hstack((d,n4))

array([[ 1,  0,  0,  0,  0,  1,  3,  5,  7,  9],
       [ 0,  2,  0,  0,  0, 11, 13, 15, 17, 19],
       [ 0,  0,  3,  0,  0, 21, 23, 25, 27, 29],
       [ 0,  0,  0,  4,  0, 31, 33, 35, 37, 39],
       [ 0,  0,  0,  0,  5, 41, 43, 45, 47, 49]])

In [47]:
np.vstack((d,n4))

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  5],
       [ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [52]:
s1 = np.hstack((d,n4))
s1

array([[ 1,  0,  0,  0,  0,  1,  3,  5,  7,  9],
       [ 0,  2,  0,  0,  0, 11, 13, 15, 17, 19],
       [ 0,  0,  3,  0,  0, 21, 23, 25, 27, 29],
       [ 0,  0,  0,  4,  0, 31, 33, 35, 37, 39],
       [ 0,  0,  0,  0,  5, 41, 43, 45, 47, 49]])

In [54]:
s2 = np.vstack((d,n4))
s2

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  5],
       [ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [55]:
print(d)
print(n4)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


In [48]:
d * n4

array([[  1,   0,   0,   0,   0],
       [  0,  26,   0,   0,   0],
       [  0,   0,  75,   0,   0],
       [  0,   0,   0, 148,   0],
       [  0,   0,   0,   0, 245]])

In [49]:
q1 = np.array([1,2,3,4])
q2 = np.array([4,3,2,1])

q1 * q2

array([4, 6, 6, 4])

In [59]:
s4 = np.dot(s1,s2)

In [57]:
print(s1)
print(s2)

[[ 1  0  0  0  0  1  3  5  7  9]
 [ 0  2  0  0  0 11 13 15 17 19]
 [ 0  0  3  0  0 21 23 25 27 29]
 [ 0  0  0  4  0 31 33 35 37 39]
 [ 0  0  0  0  5 41 43 45 47 49]]
[[ 1  0  0  0  0]
 [ 0  2  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0  5]
 [ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


In [58]:
np.dot(s2,s1)

array([[   1,    0,    0,    0,    0,    1,    3,    5,    7,    9],
       [   0,    4,    0,    0,    0,   22,   26,   30,   34,   38],
       [   0,    0,    9,    0,    0,   63,   69,   75,   81,   87],
       [   0,    0,    0,   16,    0,  124,  132,  140,  148,  156],
       [   0,    0,    0,    0,   25,  205,  215,  225,  235,  245],
       [   1,    6,   15,   28,   45,  725,  775,  825,  875,  925],
       [  11,   26,   45,   68,   95, 1775, 1925, 2075, 2225, 2375],
       [  21,   46,   75,  108,  145, 2825, 3075, 3325, 3575, 3825],
       [  31,   66,  105,  148,  195, 3875, 4225, 4575, 4925, 5275],
       [  41,   86,  135,  188,  245, 4925, 5375, 5825, 6275, 6725]])

In [60]:
s4.max()

6750

In [61]:
s4.min()

726

In [62]:
s4.sum()

83180

In [64]:
s4.argmax()

24

In [65]:
s4

array([[ 726,  775,  825,  875,  925],
       [1775, 1929, 2075, 2225, 2375],
       [2825, 3075, 3334, 3575, 3825],
       [3875, 4225, 4575, 4941, 5275],
       [4925, 5375, 5825, 6275, 6750]])

In [66]:
s4.argmin()

0

In [67]:
s4.cumsum()

array([  726,  1501,  2326,  3201,  4126,  5901,  7830,  9905, 12130,
       14505, 17330, 20405, 23739, 27314, 31139, 35014, 39239, 43814,
       48755, 54030, 58955, 64330, 70155, 76430, 83180], dtype=int32)

In [71]:
c = np.array([2 + 4j])
c.dtype

dtype('complex128')

In [73]:
c = np.array([2 + 4j,6,7])
c

array([2.+4.j, 6.+0.j, 7.+0.j])

In [74]:
d.repeat(2,axis = 0)

array([[1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5],
       [0, 0, 0, 0, 5]])

In [75]:
d.repeat(2,axis = 1)

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 4, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 5, 5]])

In [76]:
np.equal(s1,s2)

ValueError: operands could not be broadcast together with shapes (5,10) (10,5) 

In [77]:
np.equal(d,d)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [78]:
d.tolist()

[[1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0],
 [0, 0, 0, 0, 5]]

In [81]:
j = np.random.rand(5,5)
j

array([[0.03426496, 0.32010656, 0.69222113, 0.28122294, 0.31502308],
       [0.85473264, 0.13712253, 0.61147038, 0.25899962, 0.75843452],
       [0.46299016, 0.16622457, 0.11232751, 0.7238013 , 0.89850459],
       [0.84227289, 0.4405778 , 0.03383119, 0.18536174, 0.04853194],
       [0.31091583, 0.73750051, 0.23429802, 0.25271819, 0.13966102]])

In [83]:
j.sort(axis = 0)
j

array([[0.03383119, 0.04853194, 0.18536174, 0.31091583, 0.69222113],
       [0.03426496, 0.16622457, 0.25271819, 0.32010656, 0.73750051],
       [0.11232751, 0.23429802, 0.31502308, 0.4405778 , 0.84227289],
       [0.13712253, 0.25899962, 0.46299016, 0.7238013 , 0.85473264],
       [0.13966102, 0.28122294, 0.61147038, 0.75843452, 0.89850459]])

In [84]:
j.sort(axis = 1)
j

array([[0.03383119, 0.04853194, 0.18536174, 0.31091583, 0.69222113],
       [0.03426496, 0.16622457, 0.25271819, 0.32010656, 0.73750051],
       [0.11232751, 0.23429802, 0.31502308, 0.4405778 , 0.84227289],
       [0.13712253, 0.25899962, 0.46299016, 0.7238013 , 0.85473264],
       [0.13966102, 0.28122294, 0.61147038, 0.75843452, 0.89850459]])

In [86]:
np.median(j)

0.31091583403633094

In [87]:
j.mean()

0.394124624037404

In [88]:
np.random.randint(1,100)

68

In [89]:
np.random.rand(5,5)

array([[0.26758016, 0.17916568, 0.04105455, 0.33579794, 0.2348993 ],
       [0.50874404, 0.21451594, 0.48642869, 0.45100438, 0.0914725 ],
       [0.62556881, 0.9308774 , 0.95928543, 0.42624184, 0.25513694],
       [0.0668618 , 0.86779327, 0.6637557 , 0.09264191, 0.55412236],
       [0.47044715, 0.24125489, 0.40819519, 0.44258442, 0.74415941]])